spring.application.name=StockManagment
server.address=0.0.0.0
server.port=8080

# --- DATABASE CONFIG ---
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ptzwqiimekmcokwfegtr
spring.datasource.password=Muhamed1000
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA CONFIG ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----Reduce Spring Boot Auto-Configuration
spring.main.lazy-initialization=true
spring.jmx.enabled=false
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false


JWT_SECRET=mysuperlongsecretkey12345678901234567890