spring.application.name=StockManagment
server.address=0.0.0.0
server.port=8080

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=StockManagement;encrypt=true;trustServerCertificate=true;

spring.datasource.username=SQLSERVER1
spring.datasource.password=Muhamed100